### ISSUE TITLE
Add talk video and presentation from 17 Jan 2019 to the repo

### ISSUE THREAD

**Issue by akarsh** [Swift-Dev-Ninjas/talks#1]
- [x] mp4 file or other video format of the talk video
- [x] if possible add presentation slides to the repo

**Comment by Gucky** [comment]
Slides and demo code uploaded. Video file prepared and ready for Youtube upload (as discussed).
Link to Youtube video needs to be added to the README.

**Comment by akarsh** [comment]
I updated the README.md file refer to commit  813e315
